# Base information
baseURL = "https://example.com"
languageCode = "en-gb"
title = "Sam Robbins"
# theme = "hugo-developer-portfolio"
googleAnalytics = ""

# Remove this when using normally
# themesDir = "../../" 
# `
[module]
  [[module.imports]]
    path = "github.com/samrobbins85/hugo-developer-portfolio"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"


# navigation
[menu]

  [[menu.main]]
  name = "About"
  URL = "about"
  weight=1

  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight=2

  [[menu.main]]
  name = "Portfolio"
  URL = "portfolio"
  weight=3

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight=4


[params]
home = "Home"
# Meta data
description = "The website of Sam Robbins, 2nd Year Computer Science Student at Durham University"
author = "Sam Robbins"


  [params.contact]
  enable = true
  formAction = "" #contact form works with formspree.io

  [params.footer]
  email = "samrobbinsgb@gmail.com"
  address = "Durham, UK"
  googlemaps = "https://www.google.com/maps/embed/v1/place?q=place_id:ChIJwbHYJaUqfEgRK0Ui9dVGimc&key=AIzaSyAE_4rVAKux_DSPcb_OdSRDaovtPOSk_3U"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "rainbow_dash"
    tabWidth = 4

