baseURL = "https://example.com"
languageCode = "en-gb"
title = "Sam Robbins"
theme = "hugo-developer-portfolio"
summaryLength = "10"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"


# navigation
[menu]
    
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2
  
  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 3
  
  [[menu.main]]
  name = "Portfolio"
  URL = "portfolio"
  weight = 4
  
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 5


[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "The website of Sam Robbins, 2nd Year Computer Science Student at Durham University"
author = "Sam Robbins"
image = "images/about/profile.jpg"


  [params.contact]
  enable = true
  formAction = "https://formspree.io/mlegaggv" #contact form works with formspree.io

  [params.footer]
  email = "samrobbinsgb@gmail.com"
  phone = ""
  address = "Durham, UK"
  googlemaps = "https://www.google.com/maps/embed/v1/place?q=place_id:ChIJwbHYJaUqfEgRK0Ui9dVGimc&key=AIzaSyAE_4rVAKux_DSPcb_OdSRDaovtPOSk_3U"

